namespace ProyectoBiblioteca
{
    partial class Inventario
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Inventario));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuPanel3 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnLimpiar = new Bunifu.UI.WinForms.BunifuImageButton();
            this.btnRefresh = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuDatePicker1 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.panel1 = new System.Windows.Forms.Panel();
            this.label5 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.Tipo_producto = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Nombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.ID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Actualizar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Eliminar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Registrar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label3 = new System.Windows.Forms.Label();
            this.Buscar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtBusqueda = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            this.bunifuGradientPanel1.SuspendLayout();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuPanel3
            // 
            this.bunifuPanel3.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(235)))), ((int)(((byte)(234)))));
            this.bunifuPanel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel3.BackgroundImage")));
            this.bunifuPanel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel3.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel3.BorderRadius = 35;
            this.bunifuPanel3.BorderThickness = 1;
            this.bunifuPanel3.Controls.Add(this.btnLimpiar);
            this.bunifuPanel3.Controls.Add(this.btnRefresh);
            this.bunifuPanel3.Controls.Add(this.bunifuDataGridView1);
            this.bunifuPanel3.Location = new System.Drawing.Point(281, 168);
            this.bunifuPanel3.Name = "bunifuPanel3";
            this.bunifuPanel3.ShowBorders = true;
            this.bunifuPanel3.Size = new System.Drawing.Size(750, 428);
            this.bunifuPanel3.TabIndex = 12;
            // 
            // btnLimpiar
            // 
            this.btnLimpiar.ActiveImage = null;
            this.btnLimpiar.AllowAnimations = true;
            this.btnLimpiar.AllowBuffering = false;
            this.btnLimpiar.AllowToggling = false;
            this.btnLimpiar.AllowZooming = true;
            this.btnLimpiar.AllowZoomingOnFocus = false;
            this.btnLimpiar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            this.btnLimpiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLimpiar.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnLimpiar.ErrorImage")));
            this.btnLimpiar.FadeWhenInactive = false;
            this.btnLimpiar.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnLimpiar.Image = global::ProyectoBiblioteca.Properties.Resources.icons8_escoba_50;
            this.btnLimpiar.ImageActive = null;
            this.btnLimpiar.ImageLocation = null;
            this.btnLimpiar.ImageMargin = 10;
            this.btnLimpiar.ImageSize = new System.Drawing.Size(31, 32);
            this.btnLimpiar.ImageZoomSize = new System.Drawing.Size(41, 42);
            this.btnLimpiar.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnLimpiar.InitialImage")));
            this.btnLimpiar.Location = new System.Drawing.Point(85, 8);
            this.btnLimpiar.Name = "btnLimpiar";
            this.btnLimpiar.Rotation = 0;
            this.btnLimpiar.ShowActiveImage = true;
            this.btnLimpiar.ShowCursorChanges = true;
            this.btnLimpiar.ShowImageBorders = false;
            this.btnLimpiar.ShowSizeMarkers = false;
            this.btnLimpiar.Size = new System.Drawing.Size(41, 42);
            this.btnLimpiar.TabIndex = 8;
            this.btnLimpiar.ToolTipText = "";
            this.btnLimpiar.WaitOnLoad = false;
            this.btnLimpiar.Zoom = 10;
            this.btnLimpiar.ZoomSpeed = 10;
            // 
            // btnRefresh
            // 
            this.btnRefresh.ActiveImage = null;
            this.btnRefresh.AllowAnimations = true;
            this.btnRefresh.AllowBuffering = false;
            this.btnRefresh.AllowToggling = false;
            this.btnRefresh.AllowZooming = true;
            this.btnRefresh.AllowZoomingOnFocus = false;
            this.btnRefresh.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            this.btnRefresh.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRefresh.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnRefresh.ErrorImage")));
            this.btnRefresh.FadeWhenInactive = false;
            this.btnRefresh.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnRefresh.Image = global::ProyectoBiblioteca.Properties.Resources.icons8_actualizar_32;
            this.btnRefresh.ImageActive = null;
            this.btnRefresh.ImageLocation = null;
            this.btnRefresh.ImageMargin = 10;
            this.btnRefresh.ImageSize = new System.Drawing.Size(31, 32);
            this.btnRefresh.ImageZoomSize = new System.Drawing.Size(41, 42);
            this.btnRefresh.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnRefresh.InitialImage")));
            this.btnRefresh.Location = new System.Drawing.Point(27, 8);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.Rotation = 0;
            this.btnRefresh.ShowActiveImage = true;
            this.btnRefresh.ShowCursorChanges = true;
            this.btnRefresh.ShowImageBorders = false;
            this.btnRefresh.ShowSizeMarkers = false;
            this.btnRefresh.Size = new System.Drawing.Size(41, 42);
            this.btnRefresh.TabIndex = 7;
            this.btnRefresh.ToolTipText = "";
            this.btnRefresh.WaitOnLoad = false;
            this.btnRefresh.Zoom = 10;
            this.btnRefresh.ZoomSpeed = 10;
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridView1.ColumnHeadersHeight = 40;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(13, 56);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.ReadOnly = true;
            this.bunifuDataGridView1.RowHeadersVisible = false;
            this.bunifuDataGridView1.RowHeadersWidth = 51;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(721, 345);
            this.bunifuDataGridView1.TabIndex = 0;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuDatePicker1);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(148)))), ((int)(((byte)(153)))), ((int)(((byte)(222)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.LightSkyBlue;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.Azure;
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(182)))), ((int)(((byte)(243)))), ((int)(((byte)(242)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(1056, 100);
            this.bunifuGradientPanel1.TabIndex = 13;
            // 
            // bunifuDatePicker1
            // 
            this.bunifuDatePicker1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuDatePicker1.BorderRadius = 15;
            this.bunifuDatePicker1.CalendarFont = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuDatePicker1.CalendarTitleBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.bunifuDatePicker1.CalendarTrailingForeColor = System.Drawing.SystemColors.GradientActiveCaption;
            this.bunifuDatePicker1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
            this.bunifuDatePicker1.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bunifuDatePicker1.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bunifuDatePicker1.DisabledColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker1.DisplayWeekNumbers = false;
            this.bunifuDatePicker1.DPHeight = 0;
            this.bunifuDatePicker1.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bunifuDatePicker1.FillDatePicker = false;
            this.bunifuDatePicker1.Font = new System.Drawing.Font("Cooper Black", 8F);
            this.bunifuDatePicker1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDatePicker1.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuDatePicker1.Icon")));
            this.bunifuDatePicker1.IconColor = System.Drawing.Color.Black;
            this.bunifuDatePicker1.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bunifuDatePicker1.LeftTextMargin = 5;
            this.bunifuDatePicker1.Location = new System.Drawing.Point(496, 64);
            this.bunifuDatePicker1.MinimumSize = new System.Drawing.Size(4, 32);
            this.bunifuDatePicker1.Name = "bunifuDatePicker1";
            this.bunifuDatePicker1.Size = new System.Drawing.Size(223, 32);
            this.bunifuDatePicker1.TabIndex = 7;
            this.bunifuDatePicker1.Value = new System.DateTime(2024, 10, 13, 0, 0, 0, 0);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Cooper Black", 24F);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel1.Location = new System.Drawing.Point(197, 22);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(702, 36);
            this.bunifuLabel1.TabIndex = 3;
            this.bunifuLabel1.Text = "INVENTARIO DE LIBROS Y COLECCIONES";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(135)))), ((int)(((byte)(216)))), ((int)(((byte)(224)))));
            this.panel1.Controls.Add(this.label5);
            this.panel1.Controls.Add(this.label7);
            this.panel1.Controls.Add(this.Tipo_producto);
            this.panel1.Controls.Add(this.Nombre);
            this.panel1.Controls.Add(this.label4);
            this.panel1.Controls.Add(this.ID);
            this.panel1.Controls.Add(this.Actualizar);
            this.panel1.Controls.Add(this.Eliminar);
            this.panel1.Controls.Add(this.Registrar);
            this.panel1.Controls.Add(this.label3);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 100);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(249, 524);
            this.panel1.TabIndex = 14;
            this.panel1.Paint += new System.Windows.Forms.PaintEventHandler(this.panel1_Paint);
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.Black;
            this.label5.Location = new System.Drawing.Point(20, 140);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(87, 19);
            this.label5.TabIndex = 30;
            this.label5.Text = "Cantidad:";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.Transparent;
            this.label7.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.Black;
            this.label7.Location = new System.Drawing.Point(22, 225);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(128, 19);
            this.label7.TabIndex = 26;
            this.label7.Text = "Fecha entrada:";
            // 
            // Tipo_producto
            // 
            this.Tipo_producto.AcceptsReturn = false;
            this.Tipo_producto.AcceptsTab = false;
            this.Tipo_producto.AnimationSpeed = 200;
            this.Tipo_producto.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Tipo_producto.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Tipo_producto.BackColor = System.Drawing.Color.Transparent;
            this.Tipo_producto.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Tipo_producto.BackgroundImage")));
            this.Tipo_producto.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Tipo_producto.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Tipo_producto.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Tipo_producto.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
            this.Tipo_producto.BorderRadius = 20;
            this.Tipo_producto.BorderThickness = 1;
            this.Tipo_producto.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Tipo_producto.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Tipo_producto.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Tipo_producto.DefaultText = "";
            this.Tipo_producto.FillColor = System.Drawing.Color.White;
            this.Tipo_producto.HideSelection = true;
            this.Tipo_producto.IconLeft = null;
            this.Tipo_producto.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Tipo_producto.IconPadding = 10;
            this.Tipo_producto.IconRight = null;
            this.Tipo_producto.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Tipo_producto.Lines = new string[0];
            this.Tipo_producto.Location = new System.Drawing.Point(15, 247);
            this.Tipo_producto.MaxLength = 32767;
            this.Tipo_producto.MinimumSize = new System.Drawing.Size(1, 1);
            this.Tipo_producto.Modified = false;
            this.Tipo_producto.Multiline = false;
            this.Tipo_producto.Name = "Tipo_producto";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Tipo_producto.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Tipo_producto.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Tipo_producto.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Tipo_producto.OnIdleState = stateProperties4;
            this.Tipo_producto.Padding = new System.Windows.Forms.Padding(3);
            this.Tipo_producto.PasswordChar = '\0';
            this.Tipo_producto.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Tipo_producto.PlaceholderText = "DD/MM/AA";
            this.Tipo_producto.ReadOnly = false;
            this.Tipo_producto.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Tipo_producto.SelectedText = "";
            this.Tipo_producto.SelectionLength = 0;
            this.Tipo_producto.SelectionStart = 0;
            this.Tipo_producto.ShortcutsEnabled = true;
            this.Tipo_producto.Size = new System.Drawing.Size(203, 42);
            this.Tipo_producto.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Tipo_producto.TabIndex = 27;
            this.Tipo_producto.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Tipo_producto.TextMarginBottom = 0;
            this.Tipo_producto.TextMarginLeft = 3;
            this.Tipo_producto.TextMarginTop = 0;
            this.Tipo_producto.TextPlaceholder = "DD/MM/AA";
            this.Tipo_producto.UseSystemPasswordChar = false;
            this.Tipo_producto.WordWrap = true;
            // 
            // Nombre
            // 
            this.Nombre.AcceptsReturn = false;
            this.Nombre.AcceptsTab = false;
            this.Nombre.AnimationSpeed = 200;
            this.Nombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Nombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Nombre.BackColor = System.Drawing.Color.Transparent;
            this.Nombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Nombre.BackgroundImage")));
            this.Nombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Nombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Nombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Nombre.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
            this.Nombre.BorderRadius = 20;
            this.Nombre.BorderThickness = 1;
            this.Nombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Nombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Nombre.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Nombre.DefaultText = "";
            this.Nombre.FillColor = System.Drawing.Color.White;
            this.Nombre.ForeColor = System.Drawing.Color.Black;
            this.Nombre.HideSelection = true;
            this.Nombre.IconLeft = null;
            this.Nombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Nombre.IconPadding = 10;
            this.Nombre.IconRight = null;
            this.Nombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Nombre.Lines = new string[0];
            this.Nombre.Location = new System.Drawing.Point(15, 162);
            this.Nombre.MaxLength = 32767;
            this.Nombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.Nombre.Modified = false;
            this.Nombre.Multiline = false;
            this.Nombre.Name = "Nombre";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Nombre.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Nombre.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Nombre.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Nombre.OnIdleState = stateProperties8;
            this.Nombre.Padding = new System.Windows.Forms.Padding(3);
            this.Nombre.PasswordChar = '\0';
            this.Nombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Nombre.PlaceholderText = "PIEZAS";
            this.Nombre.ReadOnly = false;
            this.Nombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Nombre.SelectedText = "";
            this.Nombre.SelectionLength = 0;
            this.Nombre.SelectionStart = 0;
            this.Nombre.ShortcutsEnabled = true;
            this.Nombre.Size = new System.Drawing.Size(203, 42);
            this.Nombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Nombre.TabIndex = 25;
            this.Nombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Nombre.TextMarginBottom = 0;
            this.Nombre.TextMarginLeft = 3;
            this.Nombre.TextMarginTop = 0;
            this.Nombre.TextPlaceholder = "PIEZAS";
            this.Nombre.UseSystemPasswordChar = false;
            this.Nombre.WordWrap = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.Black;
            this.label4.Location = new System.Drawing.Point(21, 57);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(65, 19);
            this.label4.TabIndex = 4;
            this.label4.Text = "ID Libro";
            // 
            // ID
            // 
            this.ID.AcceptsReturn = false;
            this.ID.AcceptsTab = false;
            this.ID.AnimationSpeed = 200;
            this.ID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ID.BackColor = System.Drawing.Color.Transparent;
            this.ID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ID.BackgroundImage")));
            this.ID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ID.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
            this.ID.BorderRadius = 20;
            this.ID.BorderThickness = 1;
            this.ID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ID.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ID.DefaultText = "";
            this.ID.FillColor = System.Drawing.Color.White;
            this.ID.HideSelection = true;
            this.ID.IconLeft = null;
            this.ID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ID.IconPadding = 10;
            this.ID.IconRight = null;
            this.ID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ID.Lines = new string[0];
            this.ID.Location = new System.Drawing.Point(15, 79);
            this.ID.MaxLength = 32767;
            this.ID.MinimumSize = new System.Drawing.Size(1, 1);
            this.ID.Modified = false;
            this.ID.Multiline = false;
            this.ID.Name = "ID";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ID.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ID.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ID.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ID.OnIdleState = stateProperties12;
            this.ID.Padding = new System.Windows.Forms.Padding(3);
            this.ID.PasswordChar = '\0';
            this.ID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ID.PlaceholderText = "1";
            this.ID.ReadOnly = false;
            this.ID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ID.SelectedText = "";
            this.ID.SelectionLength = 0;
            this.ID.SelectionStart = 0;
            this.ID.ShortcutsEnabled = true;
            this.ID.Size = new System.Drawing.Size(203, 42);
            this.ID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ID.TabIndex = 16;
            this.ID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ID.TextMarginBottom = 0;
            this.ID.TextMarginLeft = 3;
            this.ID.TextMarginTop = 0;
            this.ID.TextPlaceholder = "1";
            this.ID.UseSystemPasswordChar = false;
            this.ID.WordWrap = true;
            // 
            // Actualizar
            // 
            this.Actualizar.AllowAnimations = true;
            this.Actualizar.AllowMouseEffects = true;
            this.Actualizar.AllowToggling = false;
            this.Actualizar.AnimationSpeed = 200;
            this.Actualizar.AutoGenerateColors = false;
            this.Actualizar.AutoRoundBorders = false;
            this.Actualizar.AutoSizeLeftIcon = true;
            this.Actualizar.AutoSizeRightIcon = true;
            this.Actualizar.BackColor = System.Drawing.Color.Transparent;
            this.Actualizar.BackColor1 = System.Drawing.Color.Transparent;
            this.Actualizar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Actualizar.BackgroundImage")));
            this.Actualizar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Actualizar.ButtonText = "";
            this.Actualizar.ButtonTextMarginLeft = 0;
            this.Actualizar.ColorContrastOnClick = 45;
            this.Actualizar.ColorContrastOnHover = 45;
            this.Actualizar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.Actualizar.CustomizableEdges = borderEdges1;
            this.Actualizar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Actualizar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Actualizar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Actualizar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Actualizar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Actualizar.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Actualizar.ForeColor = System.Drawing.Color.Black;
            this.Actualizar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Actualizar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Actualizar.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.Actualizar.IconMarginLeft = 11;
            this.Actualizar.IconPadding = 5;
            this.Actualizar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Actualizar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Actualizar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Actualizar.IconSize = 25;
            this.Actualizar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Actualizar.IdleBorderRadius = 15;
            this.Actualizar.IdleBorderThickness = 1;
            this.Actualizar.IdleFillColor = System.Drawing.Color.Transparent;
            this.Actualizar.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("Actualizar.IdleIconLeftImage")));
            this.Actualizar.IdleIconRightImage = null;
            this.Actualizar.IndicateFocus = false;
            this.Actualizar.Location = new System.Drawing.Point(174, 305);
            this.Actualizar.Name = "Actualizar";
            this.Actualizar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Actualizar.OnDisabledState.BorderRadius = 15;
            this.Actualizar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Actualizar.OnDisabledState.BorderThickness = 1;
            this.Actualizar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Actualizar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Actualizar.OnDisabledState.IconLeftImage = null;
            this.Actualizar.OnDisabledState.IconRightImage = null;
            this.Actualizar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Actualizar.onHoverState.BorderRadius = 15;
            this.Actualizar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Actualizar.onHoverState.BorderThickness = 1;
            this.Actualizar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Actualizar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Actualizar.onHoverState.IconLeftImage = null;
            this.Actualizar.onHoverState.IconRightImage = null;
            this.Actualizar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Actualizar.OnIdleState.BorderRadius = 15;
            this.Actualizar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Actualizar.OnIdleState.BorderThickness = 1;
            this.Actualizar.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.Actualizar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Actualizar.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("Actualizar.OnIdleState.IconLeftImage")));
            this.Actualizar.OnIdleState.IconRightImage = null;
            this.Actualizar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Actualizar.OnPressedState.BorderRadius = 15;
            this.Actualizar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Actualizar.OnPressedState.BorderThickness = 1;
            this.Actualizar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Actualizar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Actualizar.OnPressedState.IconLeftImage = null;
            this.Actualizar.OnPressedState.IconRightImage = null;
            this.Actualizar.Size = new System.Drawing.Size(44, 46);
            this.Actualizar.TabIndex = 15;
            this.Actualizar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Actualizar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Actualizar.TextMarginLeft = 0;
            this.Actualizar.TextPadding = new System.Windows.Forms.Padding(0);
            this.Actualizar.UseDefaultRadiusAndThickness = true;
            // 
            // Eliminar
            // 
            this.Eliminar.AllowAnimations = true;
            this.Eliminar.AllowMouseEffects = true;
            this.Eliminar.AllowToggling = false;
            this.Eliminar.AnimationSpeed = 200;
            this.Eliminar.AutoGenerateColors = false;
            this.Eliminar.AutoRoundBorders = false;
            this.Eliminar.AutoSizeLeftIcon = true;
            this.Eliminar.AutoSizeRightIcon = true;
            this.Eliminar.BackColor = System.Drawing.Color.Transparent;
            this.Eliminar.BackColor1 = System.Drawing.Color.Transparent;
            this.Eliminar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Eliminar.BackgroundImage")));
            this.Eliminar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Eliminar.ButtonText = "";
            this.Eliminar.ButtonTextMarginLeft = 0;
            this.Eliminar.ColorContrastOnClick = 45;
            this.Eliminar.ColorContrastOnHover = 45;
            this.Eliminar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Eliminar.CustomizableEdges = borderEdges2;
            this.Eliminar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Eliminar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Eliminar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Eliminar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Eliminar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Eliminar.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Eliminar.ForeColor = System.Drawing.Color.Black;
            this.Eliminar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Eliminar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Eliminar.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.Eliminar.IconMarginLeft = 11;
            this.Eliminar.IconPadding = 5;
            this.Eliminar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Eliminar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Eliminar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Eliminar.IconSize = 25;
            this.Eliminar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Eliminar.IdleBorderRadius = 15;
            this.Eliminar.IdleBorderThickness = 1;
            this.Eliminar.IdleFillColor = System.Drawing.Color.Transparent;
            this.Eliminar.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("Eliminar.IdleIconLeftImage")));
            this.Eliminar.IdleIconRightImage = null;
            this.Eliminar.IndicateFocus = false;
            this.Eliminar.Location = new System.Drawing.Point(124, 305);
            this.Eliminar.Name = "Eliminar";
            this.Eliminar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Eliminar.OnDisabledState.BorderRadius = 15;
            this.Eliminar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Eliminar.OnDisabledState.BorderThickness = 1;
            this.Eliminar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Eliminar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Eliminar.OnDisabledState.IconLeftImage = null;
            this.Eliminar.OnDisabledState.IconRightImage = null;
            this.Eliminar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Eliminar.onHoverState.BorderRadius = 15;
            this.Eliminar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Eliminar.onHoverState.BorderThickness = 1;
            this.Eliminar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Eliminar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Eliminar.onHoverState.IconLeftImage = null;
            this.Eliminar.onHoverState.IconRightImage = null;
            this.Eliminar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Eliminar.OnIdleState.BorderRadius = 15;
            this.Eliminar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Eliminar.OnIdleState.BorderThickness = 1;
            this.Eliminar.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.Eliminar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Eliminar.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("Eliminar.OnIdleState.IconLeftImage")));
            this.Eliminar.OnIdleState.IconRightImage = null;
            this.Eliminar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Eliminar.OnPressedState.BorderRadius = 15;
            this.Eliminar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Eliminar.OnPressedState.BorderThickness = 1;
            this.Eliminar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Eliminar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Eliminar.OnPressedState.IconLeftImage = null;
            this.Eliminar.OnPressedState.IconRightImage = null;
            this.Eliminar.Size = new System.Drawing.Size(44, 46);
            this.Eliminar.TabIndex = 13;
            this.Eliminar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Eliminar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Eliminar.TextMarginLeft = 0;
            this.Eliminar.TextPadding = new System.Windows.Forms.Padding(0);
            this.Eliminar.UseDefaultRadiusAndThickness = true;
            // 
            // Registrar
            // 
            this.Registrar.AllowAnimations = true;
            this.Registrar.AllowMouseEffects = true;
            this.Registrar.AllowToggling = false;
            this.Registrar.AnimationSpeed = 200;
            this.Registrar.AutoGenerateColors = false;
            this.Registrar.AutoRoundBorders = false;
            this.Registrar.AutoSizeLeftIcon = true;
            this.Registrar.AutoSizeRightIcon = true;
            this.Registrar.BackColor = System.Drawing.Color.Transparent;
            this.Registrar.BackColor1 = System.Drawing.Color.Transparent;
            this.Registrar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Registrar.BackgroundImage")));
            this.Registrar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Registrar.ButtonText = "";
            this.Registrar.ButtonTextMarginLeft = 0;
            this.Registrar.ColorContrastOnClick = 45;
            this.Registrar.ColorContrastOnHover = 45;
            this.Registrar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Registrar.CustomizableEdges = borderEdges3;
            this.Registrar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Registrar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Registrar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Registrar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Registrar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Registrar.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Registrar.ForeColor = System.Drawing.Color.Black;
            this.Registrar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Registrar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Registrar.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.Registrar.IconMarginLeft = 11;
            this.Registrar.IconPadding = 5;
            this.Registrar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Registrar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Registrar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Registrar.IconSize = 25;
            this.Registrar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Registrar.IdleBorderRadius = 15;
            this.Registrar.IdleBorderThickness = 1;
            this.Registrar.IdleFillColor = System.Drawing.Color.Transparent;
            this.Registrar.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("Registrar.IdleIconLeftImage")));
            this.Registrar.IdleIconRightImage = null;
            this.Registrar.IndicateFocus = false;
            this.Registrar.Location = new System.Drawing.Point(74, 305);
            this.Registrar.Name = "Registrar";
            this.Registrar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Registrar.OnDisabledState.BorderRadius = 15;
            this.Registrar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Registrar.OnDisabledState.BorderThickness = 1;
            this.Registrar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Registrar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Registrar.OnDisabledState.IconLeftImage = null;
            this.Registrar.OnDisabledState.IconRightImage = null;
            this.Registrar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Registrar.onHoverState.BorderRadius = 15;
            this.Registrar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Registrar.onHoverState.BorderThickness = 1;
            this.Registrar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Registrar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Registrar.onHoverState.IconLeftImage = null;
            this.Registrar.onHoverState.IconRightImage = null;
            this.Registrar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Registrar.OnIdleState.BorderRadius = 15;
            this.Registrar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Registrar.OnIdleState.BorderThickness = 1;
            this.Registrar.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.Registrar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Registrar.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("Registrar.OnIdleState.IconLeftImage")));
            this.Registrar.OnIdleState.IconRightImage = null;
            this.Registrar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Registrar.OnPressedState.BorderRadius = 15;
            this.Registrar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Registrar.OnPressedState.BorderThickness = 1;
            this.Registrar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Registrar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Registrar.OnPressedState.IconLeftImage = null;
            this.Registrar.OnPressedState.IconRightImage = null;
            this.Registrar.Size = new System.Drawing.Size(44, 46);
            this.Registrar.TabIndex = 12;
            this.Registrar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Registrar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Registrar.TextMarginLeft = 0;
            this.Registrar.TextPadding = new System.Windows.Forms.Padding(0);
            this.Registrar.UseDefaultRadiusAndThickness = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.label3.ForeColor = System.Drawing.Color.Blue;
            this.label3.Location = new System.Drawing.Point(11, -3);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(7, 15);
            this.label3.TabIndex = 2;
            this.label3.Text = "\r\n";
            // 
            // Buscar
            // 
            this.Buscar.AllowAnimations = true;
            this.Buscar.AllowMouseEffects = true;
            this.Buscar.AllowToggling = false;
            this.Buscar.AnimationSpeed = 200;
            this.Buscar.AutoGenerateColors = false;
            this.Buscar.AutoRoundBorders = false;
            this.Buscar.AutoSizeLeftIcon = true;
            this.Buscar.AutoSizeRightIcon = true;
            this.Buscar.BackColor = System.Drawing.Color.Transparent;
            this.Buscar.BackColor1 = System.Drawing.Color.Transparent;
            this.Buscar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Buscar.BackgroundImage")));
            this.Buscar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Buscar.ButtonText = "";
            this.Buscar.ButtonTextMarginLeft = 0;
            this.Buscar.ColorContrastOnClick = 45;
            this.Buscar.ColorContrastOnHover = 45;
            this.Buscar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Buscar.CustomizableEdges = borderEdges4;
            this.Buscar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Buscar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Buscar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Buscar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Buscar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Buscar.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Buscar.ForeColor = System.Drawing.Color.Black;
            this.Buscar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Buscar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Buscar.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.Buscar.IconMarginLeft = 11;
            this.Buscar.IconPadding = 5;
            this.Buscar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Buscar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Buscar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Buscar.IconSize = 25;
            this.Buscar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Buscar.IdleBorderRadius = 15;
            this.Buscar.IdleBorderThickness = 1;
            this.Buscar.IdleFillColor = System.Drawing.Color.Transparent;
            this.Buscar.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("Buscar.IdleIconLeftImage")));
            this.Buscar.IdleIconRightImage = null;
            this.Buscar.IndicateFocus = false;
            this.Buscar.Location = new System.Drawing.Point(573, 127);
            this.Buscar.Name = "Buscar";
            this.Buscar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Buscar.OnDisabledState.BorderRadius = 15;
            this.Buscar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Buscar.OnDisabledState.BorderThickness = 1;
            this.Buscar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Buscar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Buscar.OnDisabledState.IconLeftImage = null;
            this.Buscar.OnDisabledState.IconRightImage = null;
            this.Buscar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Buscar.onHoverState.BorderRadius = 15;
            this.Buscar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Buscar.onHoverState.BorderThickness = 1;
            this.Buscar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Buscar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Buscar.onHoverState.IconLeftImage = null;
            this.Buscar.onHoverState.IconRightImage = null;
            this.Buscar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Buscar.OnIdleState.BorderRadius = 15;
            this.Buscar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Buscar.OnIdleState.BorderThickness = 1;
            this.Buscar.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.Buscar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Buscar.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("Buscar.OnIdleState.IconLeftImage")));
            this.Buscar.OnIdleState.IconRightImage = null;
            this.Buscar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Buscar.OnPressedState.BorderRadius = 15;
            this.Buscar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Buscar.OnPressedState.BorderThickness = 1;
            this.Buscar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Buscar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Buscar.OnPressedState.IconLeftImage = null;
            this.Buscar.OnPressedState.IconRightImage = null;
            this.Buscar.Size = new System.Drawing.Size(42, 35);
            this.Buscar.TabIndex = 14;
            this.Buscar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Buscar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Buscar.TextMarginLeft = 0;
            this.Buscar.TextPadding = new System.Windows.Forms.Padding(0);
            this.Buscar.UseDefaultRadiusAndThickness = true;
            // 
            // txtBusqueda
            // 
            this.txtBusqueda.AcceptsReturn = false;
            this.txtBusqueda.AcceptsTab = false;
            this.txtBusqueda.AnimationSpeed = 200;
            this.txtBusqueda.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBusqueda.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBusqueda.BackColor = System.Drawing.Color.Transparent;
            this.txtBusqueda.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBusqueda.BackgroundImage")));
            this.txtBusqueda.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtBusqueda.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtBusqueda.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtBusqueda.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtBusqueda.BorderRadius = 25;
            this.txtBusqueda.BorderThickness = 1;
            this.txtBusqueda.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBusqueda.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBusqueda.DefaultFont = new System.Drawing.Font("Cooper Black", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtBusqueda.DefaultText = "";
            this.txtBusqueda.FillColor = System.Drawing.Color.White;
            this.txtBusqueda.HideSelection = true;
            this.txtBusqueda.IconLeft = null;
            this.txtBusqueda.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBusqueda.IconPadding = 10;
            this.txtBusqueda.IconRight = null;
            this.txtBusqueda.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBusqueda.Lines = new string[0];
            this.txtBusqueda.Location = new System.Drawing.Point(621, 126);
            this.txtBusqueda.MaxLength = 32767;
            this.txtBusqueda.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBusqueda.Modified = false;
            this.txtBusqueda.Multiline = false;
            this.txtBusqueda.Name = "txtBusqueda";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBusqueda.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBusqueda.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBusqueda.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBusqueda.OnIdleState = stateProperties16;
            this.txtBusqueda.Padding = new System.Windows.Forms.Padding(3);
            this.txtBusqueda.PasswordChar = '\0';
            this.txtBusqueda.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtBusqueda.PlaceholderText = "Búsqueda";
            this.txtBusqueda.ReadOnly = false;
            this.txtBusqueda.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBusqueda.SelectedText = "";
            this.txtBusqueda.SelectionLength = 0;
            this.txtBusqueda.SelectionStart = 0;
            this.txtBusqueda.ShortcutsEnabled = true;
            this.txtBusqueda.Size = new System.Drawing.Size(394, 36);
            this.txtBusqueda.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtBusqueda.TabIndex = 21;
            this.txtBusqueda.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtBusqueda.TextMarginBottom = 0;
            this.txtBusqueda.TextMarginLeft = 3;
            this.txtBusqueda.TextMarginTop = 0;
            this.txtBusqueda.TextPlaceholder = "Búsqueda";
            this.txtBusqueda.UseSystemPasswordChar = false;
            this.txtBusqueda.WordWrap = true;
            this.txtBusqueda.TextChanged += new System.EventHandler(this.txtBusqueda_TextChanged);
            // 
            // Inventario
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            this.ClientSize = new System.Drawing.Size(1056, 624);
            this.Controls.Add(this.txtBusqueda);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Controls.Add(this.bunifuPanel3);
            this.Controls.Add(this.Buscar);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Inventario";
            this.Text = " ";
            this.bunifuPanel3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel3;
        private Bunifu.UI.WinForms.BunifuImageButton btnLimpiar;
        private Bunifu.UI.WinForms.BunifuImageButton btnRefresh;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox Nombre;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox ID;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Actualizar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Buscar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Eliminar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Registrar;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuDatePicker bunifuDatePicker1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox txtBusqueda;
        private Bunifu.UI.WinForms.BunifuTextBox Tipo_producto;
    }
}